# EDA On Flight Price Dataset

- This dataset have values based on object. And model only understands numeric value
- So we have to do opr to convert these values into numeric.
---

In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\myper\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\myper\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)

---

# Operation on Column: 'Date_of_journey'

In [10]:
df= pd.read_excel('flight_price.xlsx')

df['date'] = df['Date_of_Journey'].str.split('/').str[0]
df['month'] = df['Date_of_Journey'].str.split('/').str[1]
df['year'] = df['Date_of_Journey'].str.split('/').str[2]

df['date'] = df['date'].astype(int)
df['month'] = df['month'].astype(int)
df['year'] = df['year'].astype(int)

df.drop('Date_of_Journey', axis=1, inplace=True)

In [11]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

---
# Operation on Column: 'Arrival_Time'

In [83]:
# df= pd.read_excel('flight_price.xlsx')

df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(' ')[0])
df['arv_hour'] = df['Arrival_Time'].str.split(':').str[0]
df['arv_minute'] = df['Arrival_Time'].str.split(':').str[1]

df['arv_hour'] = df['arv_hour'].astype(int)
df['arv_minute'] = df['arv_minute'].astype(int)

df.drop('Arrival_Time', axis=1, inplace=True)
df.head(4)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year,arv_hour,arv_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30

---
# Operation on Column: 'Dep_Time'

In [84]:
# df= pd.read_excel('flight_price.xlsx')

df['dep_hour'] = df['Dep_Time'].str.split(':').str[0]
df['dep_minute'] = df['Dep_Time'].str.split(':').str[1]

df['dep_hour'] = df['dep_hour'].astype(int)
df['dep_minute'] = df['dep_minute'].astype(int)

df.drop('Dep_Time', axis=1, inplace=True)
df.head(4)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,date,month,year,arv_hour,arv_minute,dep_hour,dep_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,5

---
# Operation on Column: 'Total_Stops'

In [85]:
# df= pd.read_excel('flight_price.xlsx')
df['Total_Stops'].unique()
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,date,month,year,arv_hour,arv_minute,dep_hour,dep_minute
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480,6,5,2019,9,25,9,45

In [86]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0, '1 stop':1, '2 stops':2, '3 stops':3, '4 stops':4, np.nan:1})
df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,date,month,year,arv_hour,arv_minute,dep_hour,dep_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,5,50

---
# Operation on Column: 'Route'

In [87]:
df.drop('Route', axis=1, inplace=True)

---
# Operation on Column: 'Duration'

In [88]:
df['duration_hour'] = df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['duration_minute'] = df['Duration'].str.split(' ').str[1].str.split('m').str[0]

df['duration_hour'] = df['duration_hour'].fillna(0)
df['duration_minute'] = df['duration_minute'].fillna(0)
df = df[df['duration_hour'] != '5m']

df['duration_hour'] = df['duration_hour'].astype(int)
df['duration_minute'] = df['duration_minute'].astype(int)

df.drop('Duration', axis=1, inplace=True)
df.head(4)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,date,month,year,arv_hour,arv_minute,dep_hour,dep_minute,duration_hour,duration_minute
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,23,30,18,5,5,25

---
# Operation on Column: 
- 'Airline, Source, Destination, Additional_Info'

In [92]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

encoded_df = pd.DataFrame(encoder.fit_transform(df[['Airline', 'Source', 'Destination', 'Additional_Info']]).toarray(), columns=encoder.get_feature_names_out())

df = pd.concat([df, encoded_df], axis=1)

df.drop('Airline', axis=1, inplace=True)
df.drop('Source', axis=1, inplace=True)
df.drop('Destination', axis=1, inplace=True)
df.drop('Additional_Info', axis=1, inplace=True)

df.head(2)

,Total_Stops,Price,date,month,year,arv_hour,arv_minute,dep_hour,dep_minute,duration_hour,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2.0,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0