# EDA On Flight Price Dataset

- This dataset have values based on object. And model only understands numeric value
- So we have to do opr to convert these values into numeric.
---

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\myper\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\myper\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)

---

# Operation on Column: 'Date_of_journey'

In [34]:
df= pd.read_excel('flight_price.xlsx')

df['date'] = df['Date_of_Journey'].str.split('/').str[0]
df['month'] = df['Date_of_Journey'].str.split('/').str[1]
df['year'] = df['Date_of_Journey'].str.split('/').str[2]

df['date'] = df['date'].astype(int)
df['month'] = df['month'].astype(int)
df['year'] = df['year'].astype(int)

df.drop('Date_of_Journey', axis=1, inplace=True)

In [9]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

---
# Operation on Column: 'Arrival_Time'

In [35]:
# df= pd.read_excel('flight_price.xlsx')

df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(' ')[0])
df['arv_hour'] = df['Arrival_Time'].str.split(':').str[0]
df['arv_minute'] = df['Arrival_Time'].str.split(':').str[1]

df['arv_hour'] = df['arv_hour'].astype(int)
df['arv_minute'] = df['arv_minute'].astype(int)

df.drop('Arrival_Time', axis=1, inplace=True)
df.head(4)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year,arv_hour,arv_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30